version: '3.7'

services:
  app:
    image: modulotechgroup/modulotech-test-rails:dev
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - redis
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      URL: http://localhost:3000
      MODULOTECH-TEST-RAILS_DATABASE_HOST: database
      MODULOTECH-TEST-RAILS_DATABASE_NAME: modulotech-test-rails
    entrypoint: ./entrypoints/docker-entrypoint.sh
    stdin_open: true
    tty: true

  database:
    image: postgres:13.5
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: modulotech-test-rails
      LC_COLLATE: 'en_US.UTF-8'
      LC_CTYPE: 'en_US.UTF-8'

  redis:
    image: redis:6.2-alpine

  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - 1080:80


volumes:
  db_data:
