version: '3.7'

services:
  app:
    image: modulotechgroup/modulotech-test-rails
    build:
      context: .
      dockerfile: Dockerfile.prod
    depends_on:
      - database
      - redis
    ports:
      - '3000:3000'
    environment:
      RAILS_ENV: production
      URL: http://localhost:3000
      MODULOTECH_TEST_RAILS_DATABASE_HOST: database
      MODULOTECH_TEST_RAILS_DATABASE_NAME: modulotech-test-rails
      RAILS_SERVE_STATIC_FILES: 'true'

  database:
    image: postgres:13.5
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: modulotech-test-rails
      LC_COLLATE: 'en_US.UTF-8'
      LC_CTYPE: 'en_US.UTF-8'

  redis:
    image: redis:6.2-alpine

# Define the volumes references in the services
volumes:
  db_data:
